# Display name of workflow
name: Demo 03 - Jobs and Chaining

# Controls when the action will run. Workflow runs when manually triggered using the UI or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Person to greet'
        # Default value if no value is explicitly provided
        default: 'World'
        # Input has to be provided for the workflow to run
        required: true
      run-job-3:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Run job 3'
        # Default value if no value is explicitly provided
        default: true
        # Input has to be provided for the workflow to run
        required: true
        type: boolean

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  
  job1:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Send greeting
      run: echo "Job 1 - Hello ${{ github.event.inputs.name }}, run-job-3 equals ${{ github.event.inputs.run-job-3 }}"

  
  job2:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
# THE FOLLOWING TWO LINES SHOULD BE COMMENTED OUT AT THE BEGINNING OF THE DEMO
#    needs:
#     - job1

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Send greeting
      run: echo "Job 2 - Hello ${{ github.event.inputs.name }}"
      
  job3:
    if: github.event.inputs.run-job-3 == 'true'
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
# THE FOLLOWING TWO LINES SHOULD BE COMMENTED OUT AT THE BEGINNING OF THE DEMO
#    needs:
#     - job1

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Send greeting
      run: echo "Job 3 - Hello ${{ github.event.inputs.name }}"

  job4:
   # The type of runner that the job will run on
   runs-on: ubuntu-latest
# THE FOLLOWING THREE LINES SHOULD BE COMMENTED OUT AT THE BEGINNING OF THE DEMO
#   needs:
#     - job2
#     - job3

   # Steps represent a sequence of tasks that will be executed as part of the job
   steps:
   # Runs a single command using the runners shell
   - name: Send greeting
     run: echo "Job 4 - Hello ${{ github.event.inputs.name }}"