name: Demo 06 - Push To Main

on:
  workflow_dispatch:
#  comment out for the demo
#  push:
#    branches:
#      - main

jobs:
  build-app:
    name: "Build App"

    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read
      checks: write
      
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET Core 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Install dependencies
        run: dotnet restore "${{ github.workspace }}/blazorapp/BlazorApp.sln"

      - name: Build
        run: dotnet build "${{ github.workspace }}/blazorapp/BlazorApp.sln" --configuration Release --no-restore

      - name: Test
        run: |
          dotnet test "${{ github.workspace }}/blazorapp/BlazorApp.sln" --no-restore --verbosity normal  --logger "trx;LogFileName=test-results.trx"

      - name: Test Report
        uses: dorny/test-reporter@v1.7.0
        if: success() || failure()    # run this step even if previous step failed
        with:
          name: XUnit Tests            # Name of the check run which will be created
          path: ${{ github.workspace }}/blazorapp/tests/UnitTests/TestResults/*.trx    # Path to test results
          reporter: dotnet-trx
     
      - name: Publish
        run: |
          dotnet publish "${{ github.workspace }}/blazorapp/src/BlazorApp/BlazorApp.csproj" -c Release -o blazorapp

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          # Artifact name
          name: blazorappbuildartifacts
          # A file, directory or wildcard pattern that describes what to upload
          path: blazorapp/**
          # The desired behavior if no files are found using the provided path.
          if-no-files-found: error
          # Duration after which artifact will expire in days. 0 means using default retention.
          retention-days: 90


  deploy-DEV:
    name: "Deploy To Azure DEV env"

    runs-on: ubuntu-latest
    
    needs:
      - build-app
    
    environment:
      name: 'DEMO_06_DEV'
      url: 'https://blazorapp-actions-dev.azurewebsites.net'

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET Core 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Download a Build Artifact
        uses: actions/download-artifact@v4
        with:
          # Artifact name
          name: 'blazorappbuildartifacts'
          # Destination path
          path: 'blazorappbuildartifacts'
      
      # Deploy to Azure Web apps
      - name: 'Run Azure webapp deploy action using publish profile credentials'
        uses: azure/webapps-deploy@v3
        with:
          app-name: blazorapp-actions
          package: 'blazorappbuildartifacts'
          slot-name: 'dev'
  
  
  deploy-QA:
    name: "Deploy To Azure QA env"

    runs-on: ubuntu-latest
    
    needs:
      - build-app
    
    environment:
      name: 'DEMO_06_QA'
      url: 'https://blazorapp-actions-qa.azurewebsites.net'

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET Core 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Download a Build Artifact
        uses: actions/download-artifact@v4
        with:
          # Artifact name
          name: 'blazorappbuildartifacts'
          # Destination path
          path: 'blazorappbuildartifacts'
      
      # Deploy to Azure Web apps
      - name: 'Run Azure webapp deploy action using publish profile credentials'
        uses: azure/webapps-deploy@v3
        with:
          app-name: blazorapp-actions
          package: 'blazorappbuildartifacts'
          slot-name: 'qa'
          

  deploy-PROD:
    name: "Deploy To Azure PROD env"

    runs-on: ubuntu-latest
    
    needs:
      - deploy-dev
      - deploy-qa
    
    environment:
      name: 'DEMO_06_PROD'
      url: 'https://blazorapp-actions.azurewebsites.net'

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET Core 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Download a Build Artifact
        uses: actions/download-artifact@v4
        with:
          # Artifact name
          name: 'blazorappbuildartifacts'
          # Destination path
          path: 'blazorappbuildartifacts'
      
      # Deploy to Azure Web apps
      - name: 'Run Azure webapp deploy action using publish profile credentials'
        uses: azure/webapps-deploy@v3
        with:
          app-name: blazorapp-actions
          package: 'blazorappbuildartifacts'