name: Demo 07 - Reusable Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-test-deploy-app:
    permissions:
      id-token: write
      contents: read
      checks: write
    uses: ./.github/workflows/build-test-deploy.yml
    secrets:
      token: ${{ secrets.GH_TOKEN }}