name: Deploy to Azure

on:
  workflow_call:
    inputs:
      url:
        required: true
        type: string
      slot:
        required: false
        type: string
      env:
        required: true
        type: string
    secrets:
      creds:
        required: true

jobs:

  deploy:
    name: "Deploy To Azure ${{ inputs.env }} env"
    
    runs-on: ubuntu-latest
    
    environment:
      name: ${{ inputs.env }}
      url: ${{ inputs.url }}
    
    steps:
      - uses: actions/checkout@v4
  
      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.creds }}
  
      - name: Download a Build Artifact
        uses: actions/download-artifact@v4
        with:
          # Artifact name
          name: 'blazorappbuildartifacts'
          # Destination path
          path: 'blazorappbuildartifacts'
      
      # Deploy to Azure Web apps
      - name: 'Run Azure webapp deploy action using publish profile credentials'
        uses: azure/webapps-deploy@v3
        with:
          app-name: blazorapp-actions
          package: 'blazorappbuildartifacts'
          slot-name: ${{ inputs.slot || ''}}
